### ISSUE TITLE
[High Priority] New Functionality: Ability to add news and events the the News & Events page 

### ISSUE THREAD

**Issue by nicudy** [seng426-team3/vega-spring#1]
Estimation: 13 points

Admin and staff users should be able to add newsletters and events to the news & events page so that news and events can be shared and viewed by any other user.

When an admin user navigates to the news & events page, they can click on a “+” icon to add a new post.
A window should appear that prompts them to input the title and body of the news or event post they would like to add.
They can click the “post” button at the bottom of the window to add the news or event post.
They can now see the added post on the news & events page.
All users can now see the added post on the news & events page.
Public and registered users can view News & Events posts but cannot add new posts.

**Comment by kianapaz** [comment]
Closing with 12 hours of time estimation.
