### ISSUE TITLE
[Low] Bug: Footer Shifts on Different Pages

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#10]
# Bug: Footer Shifts on Different Pages

Estimation: 2 points

## Description:
- The horizontal position of the footer on the "Platform" page is different then the "Contact Us" and "Login/SignUp" pages.

## Associated User Stories:
**Scenario:** A regular site visitor is on the Vega Absolute site and explores the links at the bottom of the Vega Absolute site. 
>**Given** the regular site visitor is on the site
>**When** the regular site visitor selects the bottom of the page links.
>**Then** the site directs the user to the proper link.

## To Reproduce:
- Change your page from the "Platform" page to either the "Contact Us" or "Login/SignUp" page.

## Expected Behavior:
- While the vertical position is expected to change, the horizontal position is expected to be consistent for all page of the app the footer is present.

## System Information:
- Windows 10
- Chrome

**Comment by kianapaz** [comment]
Closing with time estimation 30 minutes. This issue doesn't have tests as it is related to styling and preference rather than a feature implementation.
