### ISSUE TITLE
[High] Bug: Login Page Not Handling Errors on Incorrect Logins

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#11]
# Bug: Login Page Not Handling Errors on Incorrect Logins

Estimation: 5 points

## Description:
- When an incorrect login is entered, the login page throws a TypeError.

## Associated User Stories:
**Scenario:** User logs into their account
>**Given** I am a registered user of Vega Absolute
>**And** I am on the “Login” page
>**When** I input my username/email address
>**And** I input my password
>**And** I click “Submit”
>**Then** I am logged in successfully if my credentials are correct.

## To Reproduce:
- Login using an invalid username or password

## Expected Behavior:
- The page should handle the error and give feedback to the user (ex. incorrect password or invalid username)

## System Information:
- Windows 10
- Chrome

**Comment by kianapaz** [comment]
Closing with 6 hours of work.
