### ISSUE TITLE
[Moderate] Invalid: Labels on Front Page Slide Show Have Stock Values

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#12]
# Invalid: Labels on Front Page Have Stock Values

Estimation: 1 point

## Description:
- The text displayed on the front page slide show are all the default values, with no information about the company.

## To Reproduce:
- Start the web app and look at the slide show while on the front page

## Associated User Stories:
- None

## Expected Behavior:
-The text during the slide show would contain information about Vega and it's products

## System Information:
- Windows 10
- Chrome

**Comment by kianapaz** [comment]
Closing with time estimation 10 mins

**Comment by kianapaz** [comment]
Closing with time estimation 10 minutes. No tests were added because this is related to styling and css and not feature implementation.
