### ISSUE TITLE
[Low] Invalid: No Message for Admin When Enable User is Clicked

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#13]
# Invalid: No Message for Admin When Enable User is Clicked

Estimation: 2 points

## Description:
- When enable user is clicked by an admin, no message is displayed for confirmation.

## Associated User Stories:
**Scenario:** Admin changes user to staff
>**Given** I am an admin
>**And** I am logged into my account
>**And** I am on the “Admin” page
>**When** I select a user I wish to update to staff
>**And** I select the role “Staff”
>**And** I click “Confirm”
>**Then** a confirmation message appears stating the user was updated
>**And** the user’s account now has staff privileges

**Scenario:** Admin activates new user account
>**Given** I am an admin
>**And** I am logged into my account
>**And** I am on the “Admin” page
>**When** I select a new user waiting for activation
>**And** I select the role “User”
>**And** I click “Enable this User”
>**Then** a confirmation message appears stating the user was activated
>**And** the user’s account now has access to services

## To Reproduce:
- While logged in as an admin click enable user
- No feedback will appear to show that this option has been selected

## Expected Behavior:
- A message should appear to confirm to the admin that this option has been selected

## System Information:
- Windows 10
- Chrome

**Comment by AntonNiko** [comment]
Fixed by https://github.com/seng426-team3/vega-web/pull/15 Actual effort: 5 points
