### ISSUE TITLE
[Moderate] Bug/Invalid: No 404 Page to Redirect to if the URL Does Not Exist

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#15]
# Bug/Invalid: No 404 Page to Redirect to if the URL Does Not Exist

Estimation: 5 points
Actual effort: 2 points

## Description:
- If a url is entered into the web app that does not exist the users are shown a blank page

## Associated User Stories:
None

## To Reproduce:
- Enter an invalid url to the web apps url

## Expected Behavior:
- The users should be directed to a 404 not found page

## System Information:
- Windows 10
- Chrome

**Comment by AntonNiko** [comment]
Closing this as that was solved by code in https://github.com/seng426-team3/vega-spring/issues/34 and PR https://github.com/seng426-team3/vega-spring/pull/35
