### ISSUE TITLE
[Moderate] Invalid: File Upload Gives No Feedback to Admin When a File is Uploaded

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#16]
# Invalid: File Upload Gives No Feedback to Admin When a File is Uploaded

Estimation: 2 points

## Description:
- When a file is uploaded no feedback is given to an admin if the file was uploaded or not

## Associated User Stories:
**Scenario:** Admin uploads a file
>**Given** I am an admin
>**And** I am logged into my account
>**And** I am on the “Resources” page
>**When** I click “Select a File”
>**And** I select a file to upload
>**And** I click “Upload”
>**Then** a confirmation message appears that the file was uploaded
>**And** staff can access the new file on the “Resources” page

## To Reproduce:
- Upload a file while signed in as an admin

## Expected Behavior:
- Feedback is returned to confirm that a file has been uploaded or failed

## System Information:
- Windows 10
- Chrome

**Comment by AntonNiko** [comment]
Fixed by https://github.com/seng426-team3/vega-web/pull/20. Actual effort: 3 points
