### ISSUE TITLE
[Low] Bug: Top Banner Does Not Show Up On Chrome

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#17]
# Bug: Top Banner Does Not Show Up On Chrome

Estimation: 2 points

## Description:
- When the web app is opened on Chrome, the top banner is not displayed

## Associated User Stories:
None

## To Reproduce:
- Open the web app on a chrome browser

## Expected Behavior:
- The banner should be visible on all browsers

## System Information:
- Windows 10
- Chrome

**Comment by skosman** [comment]
Actual Effort: 1 point
