### ISSUE TITLE
[High] Bug: Admin Can Set Their Own Role as User and Lose Access to the Admin Panel

### ISSUE THREAD

**Issue by BrodyGimson** [seng426-team3/vega-spring#18]
# Bug: Admin Can Set Their Own Role as User and Lose Access to the Admin Panel
Estimation: 3 points

## Description:
- When logged into the admin account, the admin can change their role in the Admin Panel to a User or Staff member. Doing so loses access to the Admin Panel.
## To Reproduce:
- Log into admin account
- Go to "Admin" page
- Change role for admin account to User or Staff
- Click "Enable User" with role selected
- Refresh page to see panel is no longer accessible
## Associated User Stories:
**Scenario:** Admin views registered users
>**Given** I am an admin
>**And** I am logged into my account
>**And** I am on the “Admin” page
>**When** I select a user I wish to view details for 
>**Then** a new window will be opened
>**And** all relevant user information is displayed in that window
## Expected Behavior:
- Error message is displayed to prevent role change on admin account
## System Information:
- Ubuntu 22.04
- Chrome

**Comment by AntonNiko** [comment]
Closed, solved by https://github.com/seng426-team3/vega-web/pull/30. Actual effort is 5 points.
