### ISSUE TITLE
[Moderate] Bug: User can Visit Admin Panel Page

### ISSUE THREAD

**Issue by BrodyGimson** [seng426-team3/vega-spring#19]
# Bug: User can Visit Admin Panel Page
Estimation: 2 points
Actual effort taken: 3 points

## Description:
- User can visit Admin panel by typing the URL for the page in their browser. The table of users is empty, but the column names are provided
## Associated User Stories:
**Scenario:** User tries to see admin page through URL
>**Given** I am a user
>**When** I type the admin page URL into my browser
>**Then** a “Page not found” message should be displayed
## To Reproduce:
- Go to the admin panel URL ("/adminpanel") as any user role
## Expected Behavior:
- Error message is displayed stating page not found for users that are not an admin
## System Information:
- Ubuntu 22.04
- Chrome

**Comment by AntonNiko** [comment]
Closed as PR has been merged.
