### ISSUE TITLE
[High Priority] New Functionality: Ability to edit news and events on the the News & Events page

### ISSUE THREAD

**Issue by nicudy** [seng426-team3/vega-spring#2]
Estimation: 13 points

Admin and staff users should be able to edit newsletters and events on the news & events page so that they can update or fix problems with a post.

1. When an admin user navigates to the news & events page, they can click on a “edit” button to edit a new post.
2. A window should appear that prompts them to edit the title and body of the news or event post they would like to edit.
3. They can click the “done” button at the bottom of the window to finish editing the post.
4. They can now see the edited post on the news & events page.
5. All users can now see the edited post on the news & events page.

**Comment by kianapaz** [comment]
Closing with time estimation of 7 hours
