### ISSUE TITLE
[High Priority] New Functionality: Vega Absolute Vault, Ability for Users to Manage their Secrets

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#4]
Estimation: 21 points

- User should be able to add a new secrets.
- Secret Entry should contain the following information:
     - Name of the secret
     - Date/time of the secret when secret was created.
     - Data -- text, image, file, encrypted keys.
- On Manage Secret screen. User will see a list of secret entries.
- While sending over the network, secret will be encrypted.
- Secrets will be encrypted before saving to the database.
- Users can share that secret with other people.
- Users can perform all CRUD(Create/Read/Update/Delete) operations on secret entry.
- Users should be able to filter Secret entries by entry date (date from / date to).

### Frontend:
- [x] Add Vault link to toolbar
- [x] Add Vault page for users
- [x] Add vault page for admin
- [x] Add login or create account page for non-users
- [x] Have filter option for secrets list by date
- [x] Have a share function of secrets
- [x] Have button and form to create new secrets
- [x] Have form to update secrets
- [x] Manage Secrets button which enables delete, and update
- [ ] (STRETCH GOAL) Have multi-select functions for management

### Backend:
- [x] Handle transmission of data from frontend to spring app

### Spring:
- [x] Apply appropriate role permissions
- [x] Come up with database schema for storing secrets
- [ ] Get encryption for data being stored
- [x] Handle secret creation
- [x] Handle secret reading
- [x] Handle secret updating
- [x] Handle secret deleting
- [x] Handle secret sharing

**Comment by BrodyGimson** [comment]
Basics for secret creation, deletion, and listing are complete along with which roles can access them. Need to still deal with the data portion, updating an entry, and reading a file (requires data portion to be working).

**Comment by BrodyGimson** [comment]
File portion now working. Need to get updating and encryption completed

**Comment by JesseLacroix** [comment]
Closed Issue, 34 points

**Comment by JesseLacroix** [comment]
Closed issue, 34 points
