### ISSUE TITLE
[High] Admin cannot upload resources for Staff to view

### ISSUE THREAD

**Issue by BrodyGimson** [seng426-team3/vega-spring#42]
**Scenario:** Admin uploads a file
	**Given** I am an admin
	**And** I am logged into my account
	**And** I am on the “Resources” page
	**When** I click “Select a File”
	**And** I select a file to upload
	**And** I click “Upload”
	**Then** a confirmation message appears that the file was uploaded
	**And** staff can access the new file on the “Resources” page

**Comment by AntonNiko** [comment]
Confirmed that we can upload files to resources now. Actual effort: 8 points. Solved by https://github.com/seng426-team3/vega-spring/pull/47 and https://github.com/seng426-team3/vega-web/pull/20
