### ISSUE TITLE
[High] Staff cannot view resources in resources tab

### ISSUE THREAD

**Issue by BrodyGimson** [seng426-team3/vega-spring#43]
Issue may not be a problem as no resources can be currently uploaded to confirm functionality (issue #42).

**Scenario:** Employee checks the files in the Resources section of Vega Absolute
		**Given** I am an employee of Vega Absolute
		**And** I have an account with employee role with Vega Absolute
		**And** I am logged into my account
		**When** I navigate to the “Resources” page of the application
		**Then** I will see a list of all files uploaded by Admin
		**And** I will have the option of viewing details of the file
		**And** I will have the option of downloading the file

**Comment by AntonNiko** [comment]
Confirmed that we can upload files to resources now. Actual effort: 8 points. Solved by https://github.com/seng426-team3/vega-spring/pull/47 and https://github.com/seng426-team3/vega-web/pull/20
