### ISSUE TITLE
[High] New Functionality: Vega Absolute Vault, Admin Role With Simple Reporting

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#5]
Estimation: 8 points

- Admin can see a screen with all added secret entries of all users and manage existing secret entries (read, update, create, delete). 
- Admin should also see the report screen with the following information:
     - Number of added entries in the last 7 days vs. added entries the week before that. Please Include the current day in those stats. 
     - A regular user should not be able to access this reporting screen or access its data.
- Ensure a user can add a maximum number of Secret per day. Adding more will result in error on screen. Admin will set the limit for each user.

**Comment by BrodyGimson** [comment]
Issue has been chosen not to be completed as project only requires 2 new features instead of 3.
