### ISSUE TITLE
[Moderate] [Invalid] Found bug: Contact form does not store information in backend for staff/admin to view & respond 

### ISSUE THREAD

**Issue by AntonNiko** [seng426-team3/vega-spring#66]
# Bug: Admin has option to enable users who are already enabled
Estimation: 5 points

## Description:
- When logged into the admin account, the admin can view users who are enabled, with the option to enable them. They are already enabled user, and so there should not be an option to enable the user again. Instead there should be an option to disable users.

## To Reproduce:
- Go to "Contact us" page
- Enter valid input and submit form
- Log in as "admin" or "staff" and attempt to find the submitted form content.
- No location will be visible to view submit contact requests

## Associated User Stories:
The following user story has been created to showcase expected behavior:
**Scenario (US-2-29-1) (logged as bug, not implemented in Milestone 3):** Admin and Staff, and User must be able to view submitted contact forms and respond to them in Vega Absolute
> **Given** I am a registered admin or staff
> **And** I am logged in
> **And** I am on the page which shows all the submitted contact requests
> **When** I select to respond to the visitor’s contact request
> **And** I write a message as a reply to their request
> **Then** The original user who submitted the contact form will receive a reply.

The following user story assumes that the contact us form works properly (US-2-29), and is related to this bug:
**Scenario (US-2-29)**: Visitor, Admin, Staff, and User must be able to submit contact us form when all fields are populated properly
> **Given** I am any visitor or user on Vega Absolute
> **And** I am on the “Contact Us” page of Vega Absolute
> **When** I fill in all the fields in the form correctly in the right format
> **And** I click “Submit”
> **Then** My request is successfully submitted 
> **And** I receive an alert informing me that my request has been successfully sent

## Expected Behavior:
- Contact us form should store information about submitted contact form to the application for staff and admin to view.

## System Information:
- Ubuntu 22.04
- Chrome

**Comment by kianapaz** [comment]
Closing with time estimation 7 hours.
