### ISSUE TITLE
[Moderate] Bug: Contact Us Checks for Email in Name Field

### ISSUE THREAD

**Issue by JesseLacroix** [seng426-team3/vega-spring#7]
# Bug: Contact Us Checks for Email in Name Field
Estimation: 2 points

## Description:
- When a users information is entered into the "Contact Us" form, the name field checks for an email address.

## Associated User Stories:
**Scenario:** Regular site visitor contacts Vega Absolute by sending a message
>**Given** I am on the “Contact us” page of Vega Absolute
>**When** I input my name in the “Name” text input field
>**And** I input my email address in the “Email” text input field
>**And** I input some text in the “Message” text input field
>**And** I click “Submit” on the contact form
>**Then** My message will be sent successfully to Vega Absolute
>**And** I will be redirected to the “Contact us” page of Vega Absolute

## To Reproduce:
- Enter a string into the name field that is not an email address.

## Expected Behavior:
- The name field does not limit the entries to email addresses and can accept any name.

## System Information:
- Windows 10
- Chrome

**Comment by kianapaz** [comment]
Closing ticket. Time spent ~5 hours.
